### ISSUE TITLE
 Fav or remember

### ISSUE THREAD

**Issue by surfzoid** [qishibo/github-release-statistics#28]
Hi, 
could you please either add the "remember" function of the url field or a favorite function, or github url as argument to https://qii404.me/github-release-statistics/xxxx?mygithub.repo

**Comment by qishibo** [comment]
try this
https://qii404.me/github-release-statistics/?repo=/qishibo/AnotherRedisDesktopManager/

**Comment by surfzoid** [comment]
i thank yu
